version: "3"

x-linux_x86_64_common: &linux_x86_64_common
  volumes:
    - .:/repo
  working_dir: /repo
  command: bash -c "pip install ${WHEEL} && pytest -v tests && cd example && python3 match.py"

services:
  linux_x86_64_python_36:
    <<: *linux_x86_64_common
    build:
      dockerfile: docker/python36/buster.Dockerfile
      context: .

  linux_x86_64_python_37:
    <<: *linux_x86_64_common
    build:
      dockerfile: docker/python37/buster.Dockerfile
      context: .

  linux_x86_64_python_38:
    <<: *linux_x86_64_common
    build:
      dockerfile: docker/python38/buster.Dockerfile
      context: .

  linux_x86_64_python_39:
    <<: *linux_x86_64_common
    build:
      dockerfile: docker/python39/buster.Dockerfile
      context: .
